### ISSUE TITLE
Create Vagrant File for customers

### ISSUE THREAD

**Issue by alekhrshah** [devops-alpha-s17/customers#1]
As a product owner
- I need a vargrant file for the customers part of the project
- So that we can quickly provision complex configurations consistently with repeatability

**Comment by MaskyYoung** [comment]
I think we can just use the vagrant file given by the professor

**Comment by KehanWu** [comment]
Clone the project to your development folder and create your Vagrant vm

$ git clone https://github.com/nyu-devops/lab-restful-flask.git
$ cd lab-restful-flask
$ vagrant up
Once the VM is up you can use it with:

$ vagrant ssh
$ cd /vagrant
$ python server.py
When you are done, you can use Ctrl+C to stop the server and then exit and shut down the vm with:

$ exit
$ vagrant halt
