### ISSUE TITLE
Run the demo code on Bluemix following the instructions on slide

### ISSUE THREAD

**Issue by MaskyYoung** [devops-alpha-s17/customers#23]
**As a product owner**

I want every team member to get familiar with the deployment procedures to  bluemix

so that it will be easy for us to run our own code on the bluemix.

**## Assumptions**

• Follow the instructions of the slide and be careful of the content of the manifest file which should be in consistent of our own workshop on bluemix.

## **Acceptance Criteria**
• Get the same outcomes with the slides

##Story #

**Comment by arunabh-arnav** [comment]
Looks like @alekh16 and myself have completed this step, If @MaskyYoung and @KehanWu , you guys are done, maybe we can move this to 'Done'.
