### ISSUE TITLE
Create a Auto-renew pipeline for bluemix

### ISSUE THREAD

**Issue by MaskyYoung** [devops-alpha-s17/customers#24]
**As a product owner**

I want to create a auto-renew pipeline for the bluemix workshop

so that my code can be synchronized. 

**## Assumption**

Create the pipeline successfully following the slides

**## Acceptance Criteria**

The changes of the code can be submitted on bluemix automatically

##Story #

**Comment by arunabh-arnav** [comment]
This one is also working for me. Guys let me know once we have all tried this and we'll move it to finished.
