### ISSUE TITLE
Testing all the CRUD functions on the bluemix

### ISSUE THREAD

**Issue by MaskyYoung** [devops-alpha-s17/customers#36]
As a product owner

I want to test the CRUD functions on the bluemix to make sure our code run correctly

so that the following part can be run.

##Story #

**Comment by arunabh-arnav** [comment]
1) Created 8 customers with POST method. Success.
2) Read the 8 customers with GET method. Success.
3) Read customer with id. http://nyu-customers-service-alpha.mybluemix.net/customers/11. Success.
4) Changed a field value of a customer with PUT method, it created a new customer without a new ID with changed field value. Success.
5) Deleted a customer with id. http://nyu-customers-service-alpha.mybluemix.net/customers/4. Success
6) CRUD functionalities successfully tested
